### ISSUE TITLE
B2

### ISSUE THREAD

**Issue by pujiaxun** [heihaheiha/web_tasks#3]
有bug或者如何，该有的代码还是要有。

Git的亮点就在于版本控制，到现在就提交了一个txt，可以理解成你其他的进度为0，这样就没有充分利用好
 Git 的历史版本控制的功能。

即使你提交的代码是半成品，至少也让我看到你的进度，了解你的情况，额外花了多久修复bug等等。

下次要注意～

**Comment by heihaheiha** [comment]
哦哦，好的好的，学长，下次一定注意，正在改，今晚应该能搞定

**Comment by hellotuitu** [comment]
- 注册功能报错, 原因`@user.update(password: Digest::SHA1.hexdigest(userSign_pass))`这行代码, 你的block里只有`@user1`, 没有`@user`.话说任务提交之前自己没有测试一下功能吗?顺便说一下, 注册时的密码应该是要有二次验证的, 以防用户错输.
- 添加留言报错, 但这个错误和添加留言应该没什么关系, 你自己测试的时候应该也碰到过了...`could not obtain a connection from the pool within 5.000 seconds (waited 5.000 seconds); all pooled connections were in use`, 解决方法是在每次请求处理完毕之后关闭active_record连接.
- 添加留言时(post)没有判断用户是否登录, 直接使用了`session['name']`, 我伪造post请求代码就报错了.好像几乎所有的post请求都没有判断登录?
- 修改密码那里有严重漏洞, 为什么登录之后还要输入用户名呢?如果我改密码时输入别人的用户名呢?并且改密码也应该有二次确认的.
```ruby
userLogin_name = params[:userLoginName].to_s
  userOld_pass = params[:userOldPass].to_s
  userNew_pass = params[:userNewPass].to_s
  loginUser = User.find_by(username: userLogin_name)
```
- 有些地方的代码很迷惑
```ruby
 #　登录post时
  userLogin_name = params[:userLoginName]
  userLogin_pass = params[:userLoginPass]
  users = User.all # 这行是干嘛的?
  loginUser = User.find_by(username: userLogin_name)

 # configure中
  infomations = Message.all #这一行和下一行?
  users = User.all
```
- 所有的代码都堆砌在一个文件里面, 这样很不好, 把表的创建, 数据库连接, model的定义放在另一个文件中更好.

代码逻辑有一些问题, 还有一些问题完全是粗心导致的, 这很不应该.其他方面都挺好的.

**Comment by heihaheiha** [comment]
1.注册功能报错那句话，临时觉得可以这样更改，然后其余已经修改好了，就没有测试了，二次验证功能加上了，如果用户两次输入密码不对将会进行报错提醒
2.手动加上断开连接
3.我一直以为只有get请求才能自己通过url来进行访问，post只能通过表单提交的方式去访问，所以所有的post请求都没有判断是否登录
4.修改密码已经把登录名作为已知条件加上，和忘记密码的情况弄错了
5.users = User.all 
infomations = Message.all #这一行和下一行?
  users = User.all
这三行是没有用的，和当初想得有点不同，没有作用，后来没有删除
6.最后一条正在找......
辛苦你了，真的很感谢

**Comment by hellotuitu** [comment]
改完都挺不错的~
